### PR TITLE
Use `@action/core` for logging and outputs

### LINKED ISSUE #5: Use @actions/core
Currently everything is handled manually via `console.log` and `process.exit`. This should be handled by [@actions/core](https://github.com/actions/toolkit/tree/master/packages/core)

### PR DESCRIPTION
**Pull request by notlmn**
Closes #5

Using `core.warning()` in cases where exiting without creating a tag, `core.debug()` otherwise.

### CODE REVIEW

**Comment by fregante** [comment]
Thanks @notlmn!

**Comment by notlmn** [comment]
This should also allow us to work on #10 and #13, for which I'll be raising PR's when this gets merged.

Haven't tested this PR out yet though.

**Comment by notlmn** [comment]
### Tests

With tagged HEAD: https://github.com/notlmn-dump/github-playground/actions/runs/179521168
With non-tagged HEAD: https://github.com/notlmn-dump/github-playground/actions/runs/179532683
On pushing tag: https://github.com/notlmn-dump/github-playground/actions/runs/179537414

**Comment by fregante** [comment]
Looks good! But the “tag push” event should not use warning; I think the correct (semi-silent) version would be `core.debug()`

**Comment by notlmn** [comment]
There's one small issue, I can't understand why `core.debug()` statements don't show up in logs.

Eg: `HEAD isn’t tagged. 'daily-version-action' will create '20.7.23.824'` should be printed [here](https://github.com/notlmn-dump/github-playground/runs/901822620?check_suite_focus=true#step:3:1).

**Comment by fregante** [comment]
This is the reason and workaround: https://github.com/actions/toolkit/blob/master/docs/action-debugging.md

But I think there’s a third option that we should use: core.info()

**Comment by notlmn** [comment]
> But I think there’s a third option that we should use: core.info()

`core.info()` it is then.

--------------

> But the “tag push” event should not use warning

Yeah, moving them to `core.info()` as well.

**Pull request merged**
